Use proper script template

diff --git a/utils/build b/utils/build
--- a/utils/build
+++ b/utils/build
@@ -1,8 +1,72 @@
-#!/bin/sh
+#!/bin/bash
+set -euo pipefail
 
-# set -x
+script=$(basename "$0")
+srcdir=$(readlink -f "$(dirname "$0")")
+readonly LOG_FILE="/tmp/$script.log"
+_p() { l=$1; shift; echo "$l $script: $*" | tee -a "$LOG_FILE" >&2; }
+pt() { _p "[TRACE]  " "$*";                                         }
+pd() { _p "[DEBUG]  " "$*";                                         }
+pi() { _p "[INFO]   " "$*";                                         }
+pw() { _p "[WARNING]" "$*";                                         }
+pe() { _p "[ERROR]  " "$*";                                         }
+pf() { _p "[FATAL]  " "$*"; exit 1;                                 }
 
-build=$1
+usage() {
+    cat <<EOT
+$script --help
+$script --trace --verbose --force [sw]
+EOT
+    exit 0
+}
+
+cleanup() {
+    declare -r res=$?
+    ((verbose)) && pi "Cleaning up"
+    exit $res
+}
+
+PATH="$srcdir:$PATH"
+verbose=0
+force=0
+j=16
+b=__build__
+
+while [ $# -gt 0 ]; do
+    pi "in [$1]"
+    case "$1" in
+        -h|--help)
+            usage
+            shift
+            ;;
+        -t|--trace)
+            set -x
+            shift
+            ;;
+        -v|--verbose)
+            verbose=1
+            shift
+            ;;
+        -f|--force)
+            force=1
+            shift
+            ;;
+        -j|--jobs)
+            j="$2"
+            shift 2
+            ;;
+        -b|--build)
+            b="$2"
+            shift 2
+            ;;
+        *)
+            build="$1"
+            shift
+            break
+            ;;
+    esac
+done
+
 if [ "$build" ]; then
     dir=$(ghq list -p | grep -w "$build$")
     if [ "$dir" ]; then
@@ -10,12 +74,7 @@ if [ "$build" ]; then
     fi
 fi
 
-j=16
-b=__build__
-
-set -e
-
-echo build "${build:=$(basename "$(pwd)")}"
+pi build "${build:=$(basename "$(pwd)")}"
 
 sw=$HOME/g/sw
 mkdir -p "$sw/bin"
@@ -28,14 +87,14 @@ configure() {
 
 exit_unless_x() {
     if ! DISPLAY=:0 xset q > /dev/null 2>&1; then
-        echo "not running under X, ignoring $build"
+        pi "not running under X, ignoring $build"
         exit
     fi
 }
 
 exit_if_vm() {
     if [ "$ISVM" ]; then
-        echo "running as VM, ignoring $build"
+        pi "running as VM, ignoring $build"
         exit
     fi
 }
@@ -54,13 +113,15 @@ case "$build" in
         ;;
     htop)
         v=$(git tag | grep -v beta | tail -1)
-        [ "$v" = "$(htop --version | head -1 | awk '{print $2}')" ] && exit
+        ((force)) || { \
+            [ "$v" = "$(htop --version | head -1 | awk '{print $2}')" ] && exit;
+        }
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         install_pkg libncursesw5-dev
         configure
-        make -j $j check install
+        make -j "$j" check install
         git checkout master
         ;;
     libevent)
@@ -70,16 +131,18 @@ case "$build" in
         ;;
     neovim)
         v=$(git tag | tail -1)
-        [ "NVIM $v" = "$(nvim -v | head -1)" ] && exit
+        ((force)) || { \
+            [ "NVIM $v" = "$(nvim -v | head -1)" ] && exit;
+        }
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         if [ ! "$ISOSX" ]; then
             install_pkg \
                 libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
         fi
         git clean -dxf
-        make -j $j CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$sw" \
+        make -j "$j" CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$sw" \
              CMAKE_BUILD_TYPE=Release install
              # CMAKE_BUILD_TYPE=Release test install
         git checkout master
@@ -144,14 +207,14 @@ case "$build" in
         cp ~/.zshhistory "$oldhist"
         install_pkg yodl
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         git clean -dxf
         autoreconf -vfi
         configure --enable-pcre
-        make -j $j
-        make -j $j check || echo sometimes make check fails
-        make -j $j install
+        make -j "$j"
+        make -j "$j" check || pi sometimes make check fails
+        make -j "$j" install
         git checkout master
         cp "$oldhist" ~/.zshhistory
         # run this manually if necessry
@@ -176,10 +239,10 @@ case "$build" in
         v=$(git tag | tail -1)
         [ "$v" = "v$(shellcheck --version | head -2 | tail -1 | awk '{print $2}')" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         install_pkg cabal-install
-        cabal update && cabal install --jobs=$j --prefix="$sw" && cabal clean
+        cabal update && cabal install --jobs="$j" --prefix="$sw" && cabal clean
         git checkout master
         ;;
     skype)
@@ -212,22 +275,22 @@ case "$build" in
         v=$(git tag | tail -1)
         [ "$v" = "tig-$(tig --version | head -1 | awk '{print $3}')" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         configure
-        make -j $j test || echo "make test expected to fail - don't know why"
-        make -j $j install
+        make -j "$j" test || pi "make test expected to fail - don't know why"
+        make -j "$j" install
         git checkout master
         ;;
     git)
         v=$(git tag | grep -v rc | grep '^v' | sort -V | tail -1)
         [ "$v" = "v$(git --version | awk '{print $3}')" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         install_pkg libcurl4-openssl-dev gettext
         git checkout "$(git tag | grep -v rc | grep '^v' | sort -V | tail -1)"
-        make -j $j prefix="$sw" all install
+        make -j "$j" prefix="$sw" all install
         git checkout master
         ;;
     caps2esc)
@@ -269,8 +332,8 @@ case "$build" in
         v=$(git tag | sort -V | tail -1)
         [ "$v" = "$(fzf --version | awk '{print $1}')" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         ./install --all --bin
         cp -a bin/* "$sw/bin"
         mkdir -p "$sw/etc/zsh"
@@ -283,8 +346,8 @@ case "$build" in
         v=$(git tag | grep -v '^v' | sort -V | tail -1)
         [ "$v" = "$(plenv --version | awk '{print $2}')" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         rm -f ~/.plenv
         ln -s "$(pwd)" ~/.plenv
         if [ -n "$PLENV_VERSIONS" ]; then
@@ -297,8 +360,8 @@ case "$build" in
     Perl-Build)
         v=$(git tag | tail -1)
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         mkdir -p ~/.plenv/plugins
         pb=~/.plenv/plugins/perl-build
         rm -f "$pb"
@@ -323,25 +386,25 @@ case "$build" in
         o=$(openssl version | perl -pe 's/(OpenSSL [^ ]*).*/$1/; s/[ .]/_/g')
         [ "$v" = "$o" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         git checkout "$v"
         # git checkout OpenSSL_1_0_1u
         git distclean
         # shellcheck disable=SC2016
         ./config --prefix="$sw" --openssldir="$sw/ssl" \
                  -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
-        make -j $j
-        TOP="" make -j $j test
-        make -j $j install
+        make -j "$j"
+        TOP="" make -j "$j" test
+        make -j "$j" install
         git checkout master
         ;;
     cpython)
         v=$(git tag | grep -E '^v3\.[0-9]+\.[0-9]+$' | tail -1)
         [ "$v" = "v$(python3 --version | awk '{print $2}')" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         git clean -dxf
         install_pkg build-essential git libexpat1-dev libssl-dev zlib1g-dev   \
             libncurses5-dev libbz2-dev liblzma-dev                            \
@@ -350,7 +413,7 @@ case "$build" in
             libreadline-gplv2-dev libncursesw5-dev libc6-dev libbz2-dev
         configure --enable-optimizations --enable-shared LDFLAGS=-Wl,-rpath="$sw/lib"
         # make test  # this fails on pjcj.net
-        make -j $j install
+        make -j "$j" install
         git checkout master
         ;;
     harfbuzz)
@@ -367,14 +430,14 @@ case "$build" in
         v=$(git tag | grep -v rc | sed 's/mosh-//' | tail -1)
         [ "$v" = "$(mosh --version | head -1 | awk '{print $2}')" ] && exit
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "mosh-$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "mosh-$v"
         git clean -dxf
         install_pkg                                               \
             protobuf-compiler libprotobuf-dev
         configure
-        make -j $j check || true  # can fail
-        make -j $j install
+        make -j "$j" check || true  # can fail
+        make -j "$j" install
         git checkout master
         ;;
     kitty)
@@ -408,11 +471,11 @@ case "$build" in
         [ "$v" = "$(irssi --version | awk '{print $2}')" ] && exit
         install_pkg libglib2.0-dev
         git checkout master
-        git branch -D $b || true
-        git checkout -b $b "$v"
+        git branch -D "$b" || true
+        git checkout -b "$b" "$v"
         git clean -dxf
         configure
-        make -j $j check install || true
+        make -j "$j" check install || true
         git checkout master
         ;;
     node)
@@ -433,9 +496,9 @@ case "$build" in
         sudo dpkg -i /tmp/bat.deb
         ;;
     *)
-        echo unknown build "$build"
+        pi unknown build "$build"
         exit
         ;;
 esac
 
-echo "built $build"
+pi "built $build"
